### ISSUE TITLE
nil与interface无法进行比较

### ISSUE THREAD

**Issue by younglifestyle** [stack-labs/stack-rpc#44]
https://github.com/stack-labs/stack-rpc/blob/8087580622499aa3f49420d4e4831ed11bc76e4c/pkg/config/config.go#L231

这是micro之前代码的问题，nil与interface直接进行比较，两者是比较不了的

**Comment by printfcoder** [comment]
不是很理解这个问题，当变量声明为指针但没有赋值，是可以用nil判空的。

**Comment by younglifestyle** [comment]
但其为一个接口，接口赋值为nil，只是其value被赋值为nil，结构体其他成员不为nil，所以接口不等于nil，两者比较是不等的

**Comment by younglifestyle** [comment]
https://play.golang.org/p/UpcsjEU76Xf

**Comment by printfcoder** [comment]
明白了，是指config被其它方法赋值[nil, nil]时造成的问题。确实会有这个情况。不过config模块是要初始化才能用，这个值也永远不会空。

晚点修复。点赞！

**Comment by printfcoder** [comment]
@younglifestyle 要不你来修？

**Comment by younglifestyle** [comment]
这里估计不用改，按照代码的逻辑感觉确实是不会出现问题，打扰了打扰了
